### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setAttribute' of undefined

### ISSUE THREAD

**Issue by oueryemchi** [swup/swup#206] opened 2019-09-29 20:36 UTC
I have 3 pages, all using the same script and calling SWUP lib.
The transitions work only on 2 consecutive pages, the third link gives an error:

`Uncaught TypeError: Cannot read property 'setAttribute' of undefined`

I refresh, I try other 2 random consecutive pages, the third page doesn't load giving the same error.

I have no clue what's going on..

======= UPDATE:

When popper.min.js is called in the same page, it causes the issue.
PS. popper is needed when using Bootstrap 4 JS components.

Any way to avoid conflict here?

**Comment by oueryemchi** [comment] 2019-09-29 20:51
I removed the popper.min.js :( then whatever script I use it gives me the same error after the 3 link click, here is a simple dummy test that is giving me the same issue:

`// Swup
const swup =  new Swup();

// run once 
init();

// this event runs for every page view after initial load
swup.on('contentReplaced', init);


function init() {
  if (document.querySelector('body')) {
      // something like new Carousel('#carousel')
      console.log('Run');
  }
  
  if (document.querySelector('body')) {
      // something like $('#lightbox').lightbox()
      console.log('Run');
  }
  
  if (document.querySelector('body')) {
      // ...
      console.log('Run');
  }
}`

**Comment by AugustMiller** [comment] 2019-10-01 21:59
Could you post the stack trace from the error you're seeing? Granted it went away when removing the other library, I suspect it's because it's holding on to node references that are destroyed when moving to new pages—is it possible to prevent it from initializing on load, and instead let it know about the updated DOM on each `contentReplaced` (or in your case, the existing `init()` function)?

**Comment by gmrchk** [comment] 2019-10-14 22:45
I think that Popper and swup are not really conflicting unless we have two problems causing the same error. As suggested Popper could be keeping some reference to elements that were removed from DOM, but it looks like that's not the case since the error is there even without Popper. 

If the error is coming from swup (which it probably is), it looks like the cause is a wrong HTML structure, eg. your pages have a different number of containers, so when swup is searching for containers in your page, it just finds a wrong number of it (some is missing) and so it can't set the proper attribute `data-swup` on element that is not there. 

Seeing your full swup config, or even better, an online demo would also help.

**Closed** 2019-11-01 17:59 UTC
