### ISSUE TITLE
Browser Back/Forward Button Actions Don't Animate

### ISSUE THREAD

**Issue by AdventurouslySocial** [swup/swup#139] opened 2019-05-21 17:40 UTC
I'm experiencing the consistent issue of `<html lang="en-US" class="swup-enabled">` not animating on browser history actions (back and forward buttons, are these referred to as popstates?)

In-page links do work to animate the content by adding the classes of `is-changing, is-animating, etc.` to the html tag. When I observe what's going on within Chrome element panel I can watch the html tag remain static with no classes added/removed when using the browser buttons. It should be noted that the `title` and `body` classes DO change via swup when using browser buttons. 

I don't know how to fix this. I've tried the options and I can get no solution to work. Thoughts?

**Comment by gmrchk** [comment] 2019-05-21 23:03
Hi, this is intended behavior by default. Did you check out [Animate History Browsing option](https://github.com/gmrchk/swup#animate-history-browsing)?

**Comment by AdventurouslySocial** [comment] 2019-05-22 02:03
I will explore this and report back.

**Comment by gmrchk** [comment] 2019-05-26 19:04
This info is now [here](https://swup.js.org/options#skip-popstate-handling) but the point stays. This functionality is implemented, but not used by default. 
Please, let me know if there are any problems. Closing

**Closed by gmrchk** 2019-05-26 19:04 UTC
