### ISSUE TITLE
Swup doesn't wait for transition of animation-element inside clicked a-tag

### ISSUE THREAD

**Issue by tobisalad** [swup/swup#445] opened 2022-07-14 16:22 UTC
When there's just one animation-element, which sits inside the a-tag which you click to get to another page, Swup doesnt wait for the transition to complete before replacing the container-content.

It does, however, correctly reverse-transition the same element in when entering the same page, so it does definitely identify it as an animation-element.

**Comment by daun** [comment] 2022-07-18 12:58
The intended way of using swup is to transition a container element wrapping the page content, like `div` or `main`. Can you elaborate on the use case here? What's a good reason for wrapping that in an `a` tag?

**Comment by daun** [comment] 2022-07-19 14:01
Sounds like there might be two transition properties on the element. Swup will wait for the first transition to end; e.g. if you transition the color for 200ms and the size for 400ms, the content will be replaced after 200ms.

To address your issue, I'd suggest a different solution:

- add the `transition-*` class only to the container element
- create a fixed-position div right below the body, that will be your overlay
- after swup's `clickLink` event, measure the x/y coordinates of the clicked link
- position the overlay div exactly above the clicked link, then make it grow to cover the viewport

**Comment by daun** [comment] 2022-07-19 14:56
If you're transitioning a single property, just ignore what I said 🧃

Alright, sounds reasonable. I can't reproduce the issue here, but if you can share a reproducible example on CodeSandbox or similar, we can take a closer look.

**Comment by daun** [comment] 2022-08-01 18:49
I'll close this for now as something we probably won't support. Thanks for reporting!

**Closed by daun** 2022-08-01 18:49 UTC
