### ISSUE TITLE
Back / Forward navigation not working in Instagram browser (Safari) 

### ISSUE THREAD

**Issue by svenvoskamp** [swup/swup#403] opened 2021-12-08 14:04 UTC
I have a problem when I visit the site in an Instagram browser. The navigation arrows are not active and I can't click them. Is there any way to resolve this?

**Comment by daun** [comment] 2022-03-23 13:38
Are you still seeing the issue? If you can provide a reproducible setup or a public URL that shows the mentioned behavior, we're in a better position to help.

**Comment by svenvoskamp** [comment] 2022-05-30 12:25
We're still seeing this issue. You can see the issue when you follow the step-by-step plan above. We hope you can help us.

**Comment by daun** [comment] 2022-05-30 14:09
Thanks for the clarification. I'm currently lacking the resources to look into it but am hoping to get to it at some point this summer. In the meantime, if you find a solution, we're happy to accept a pull request.

**Comment by daun** [comment] 2022-07-24 13:57
After some investigating, it looks like this is not an issue with Swup but with Instagram's specific implementation of WKWebView. All sites using the History API have the described issue, whether using Swup, Turbolinks, Barba or Page.js.

I'll have to close this issue as `wontfix` as it's out of scope of this library. However, If you happen to find a workaround, please share it here for future visitors.

**Closed by daun** 2022-07-24 13:57 UTC
Labels: bug, wontfix

**Comment by 9mm** [comment] 2022-09-23 22:07
@daun can you tell me more how you found that, or where you are finding more info on this?

I find this insane that instagram breaks everyones back buttons that use SPA's...... astounding

**Comment by daun** [comment] 2022-09-24 07:35
@9mm I tried a number of sites I've made in the past that use the different history api implementations mentioned. They all had the same issue described above. Haven't found anything official, though.

**Comment by 9mm** [comment] 2022-09-24 19:05
@daun very interesting. did you have any kind of redirect on your tests? Even something like http:// -> https:// 

I noticed that if I did a manual redirect after the document ready has finished, it would 'break' it, but if i wait until the page loads, and then do a JS redirect, it would appear to "fix" it...

**Comment by daun** [comment] 2022-09-24 21:04
@9mm Don't think so. What do you mean by manual redirect? Setting window.location via JS should work here but I probably wouldn't consider it a solution...

**Comment by 9mm** [comment] 2022-09-24 22:32
Ah, yeah there's probably no "solution" for swup, I don't even know what that is. This comment was just literally the only reference to this issue I could find online. It's a problem for our company because the URL in our instagram profile is broken when you can't use the back button, for an ecommerce site that is terrible. The only actual solution I found was to use window.location.href after the document has finished loading, and that actually jump started the navigation buttons into not being grayed out. The other thing that fixed it is opening the instagram browser settings and closing it, and that also fixes the navigation buttons (that obviously isnt a solution for a customer). The only thing so far Ive found which will fix it for a customer is doing an unecessary redirect once the document loads, and that allows the browser to bypass the bug

**Comment by daun** [comment] 2022-09-25 06:52
@9mm That‘s what surprised me as well, there‘s just nothing on this online. It‘s either unknown or it seems not to bother that many people.
