### ISSUE TITLE
[Bug]: CDN module doesn't export helpers

### ISSUE THREAD

**Issue by brokeboiflex** [swup/swup#852] opened 2023-12-16 00:15 UTC
### What did you expect? 🧐

I wanted to use `updateHistoryRecord` but it wasnt there

### What actually happened? 😵‍💫

Nothing .__.

### Swup and plugin versions 📝

- swup: 4
- ...

### URL to minimal reproduction 🔗

https://unpkg.com/swup@4.5.0/dist/Swup.umd.js

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by hirasso** [comment] 2023-12-16 09:01
Hey there! The umd build doesn't export any helpers, that's technically not possible. @daun do you know if the helpers can be accessed via cdn as well somehow? Maybe via the `?module` endpoint?

**Comment by daun** [comment] 2023-12-16 11:30
That's not a bug, just [a limitation](https://github.com/developit/microbundle/issues/712) of the bundler we're using. Combining default and named exports isn't supported out of the box and requires silly workarounds. It does have the nice side effect of keeping the bundle size low by not including all the helpers in the standalone build.

As suggested by @hirasso, the module version has all the helpers available for import. I've created a [demo repl](https://replit.com/@swupjs/Swup-Test-Exports) you can check out. That's how it looks like:

```html
<script type="module">
  import Swup, { updateHistoryRecord } from 'https://unpkg.com/swup@4?module';
  const swup = new Swup();
  updateHistoryRecord('/new-url');
</script>
```

I'll close this as not a bug, let us know if you run into any issues importing the module version.

**Closed by daun** 2023-12-16 11:30 UTC
