### ISSUE TITLE
Bug with draggable link (a tag) in Touch sliders like Glide or Flickity

### ISSUE THREAD

**Issue by riiccardo** [swup/swup#210] opened 2019-10-11 12:54 UTC
@gmrchk hi

in your showcase 

## **[Panasonic](https://plzen.cz.panasonic.com/)**

like u I'm using **`Flickity`** slider for my project but I have problem with **`links`** inside of sliders

if dragging links and release it on the current link u drag `Swup` open the link 

![Rec0001](https://user-images.githubusercontent.com/17789047/66652803-70927880-ebeb-11e9-84a6-0d341a21e445.gif)

actually I use `preventDefault` for the link with **`Flickity`** events
but `preventDefault` while dragging is not working when using `swup` links

even I add `data-no-swup` attribute while dragging but still I have problem

pls, help :'(

**Comment by riiccardo** [comment] 2019-10-11 13:09
pls add this problem to [Common Issues](https://swup.js.org/common-issues)

**Comment by gmrchk** [comment] 2019-10-14 18:28
Hi @riiccardo, 

I can see that I've faced the same issue, though as it usually is, I don't remember. The problem is not really in swup. Swup is set to trigger transition on click, which this, unfortunately, is as well.

My fix for this issue with Flickity was something like the following. I didn't test the code, but the idea should be clear. 

```javascript
let dragging = false;
const flickity = new Flickity(element, ...);

flickity.on('dragStart', () => {
    dragging = true;
});

flickity.on('dragEnd', () => {
    setTimeout(() => {
        dragging = false;
    }, 40);
});

const draggingHandler = (event) => {
    if (dragging) {
        event.preventDefault();
    }
}

element.addEventListener('touchmove', draggingHandler, { passive: false });
```

As this is the first time someone asks this question, I will keep from listing it as a common issue for now but will keep it in mind.

Since there is nothing we can do about this from swup side I will close this, but feel free to get back with your progress.

**Closed by gmrchk** 2019-10-14 18:28 UTC

**Comment by riiccardo** [comment] 2019-10-15 07:06
I thought the problem was the `flickity` slider
but I check it in [codepen](https://codepen.io/riccardo051/pen/GRRpvdy) 
`links`, while dragging and click while dragging, is fully **`preventDefault`**


thanks anyway for answer :heart_eyes:

**Comment by duncansix** [comment] 2019-10-21 16:19
FYI I have found the same issue with Flickity.

**Comment by riiccardo** [comment] 2019-10-22 16:54
@duncansix 

actually I use wired way to solve this problem

u need to add `delegate` package
https://www.npmjs.com/package/delegate

my `HTML` template
``` html
<article>
    <a class="article-link" href="/somepages.html">
        <div class="article-img">
             <img>
        </div>
        <div class="article-content">
            <h1>Article Title</h1>
            <p>Article Content</p>
        </div>
    </a>
</article>
```

``` css
/* if u want to use padding set padding to link to event.target */
.article-link {
padding: 15px;
}

/* ignore pointer event for this element to javascript just see article-link in event.target */
.article-img, article-content {
pointer-events: none;
}
```

``` javascript
      flkty.on('dragStart', function(event, pointer) {
        //const find = flkty.findAncestor(event.target, '.course-cover__card')

        console.log(event.target.nodeName)

        if (event.target.nodeName === 'A') {
          event.target.setAttribute('data-no-swup', '')
        }
      })

      flkty.on('dragEnd', function(event, pointer) {
        if (event.target.nodeName === 'A') {
          setTimeout(function() {
            event.target.removeAttribute('data-no-swup')
          }, 1)
        }
        delegate(
          document.body,
          '.course-cover__card',
          'click',
          function(e) {
            e.preventDefault()
            return false
          },
          false
        )
      })
```

**Comment by brightspire** [comment] 2019-10-23 04:25
Also having this problem. I took a similar but less elegant approach.

` $carousel.on("dragStart.flickity", function(event, pointer) {
    event.target.parentElement.setAttribute("data-no-swup", "");
  });

  $carousel.on("dragEnd.flickity", function(event, pointer) {
    setTimeout(function() {
      event.target.parentElement.removeAttribute("data-no-swup", "");
    }, 1000);
  });`

**Comment by duncansix** [comment] 2019-10-23 09:28
Thanks @ riiccardo and @brightspire. A combination of your suggestions worked for me.
