### ISSUE TITLE
Updating meta & link tags on change

### ISSUE THREAD

**Issue by DissisanOttama-Rilneme** [swup/swup#130] opened 2019-04-09 16:05 UTC
Ive been having issues with google duplicate user set canonical's, i am still working though it but i was wondering if anyone has any other experience with this?

How can i update meta & link tags on page change?

**Comment by gmrchk** [comment] 2019-04-19 22:03
Hi 👋 

Can you state what exactly is your purpose of updating the mate/link tags? I understand the link tags for specific CSS, but why meta tags?

**Comment by DissisanOttama-Rilneme** [comment] 2019-04-20 10:50
Hey!

Thanks for replying really appreciate it, I've read up extensively and seen your previous discussions on the this same issue...

Basically, I had just launched a site as google had changed its crawling, and in the search console, I was having 99% of pages excluded due to the canonical tag remaining the same through page transitions. 

To be honest, after reading your previous comments on similar issues (swapping meta tags etc...) I was convinced I was wrong, but after disabling swup I am finally starting to see pages rank, and not be excluded due to the canonical tag. 

Meta tags aren't wholly important, I just thought that it may breed a solution. 

I have also tried to use the mergehead plug in, but unfortunately cannot get it to work.

I really appreciate your time in helping with this!

THANK YOU!

**Comment by gmrchk** [comment] 2019-04-25 22:48
Interesting! Let's look into this then, although it's a bit hard thing to try out. How about trying to use a swup on a site (random newly created site with no history dropped to Netlify for example) and use swup events to replace this meta tag, and see what happens in the Google search console? 

Maybe the fact that the meta tag is there, but leaves a wrong value when transitioning with swup nowadays just is a problem. In that case, would removing the meta tag altogether fix the problem so Google can't use it as a "source of truth"? Just to be clear I don't encourage you to do so, rather trying to come up with some testing ideas.

I might be wrong, but I would be really surprised if Google was actually emulating user with running JS, but wouldn't consider at all a change of URL by replaceState/pushState as an indication that the page is not the same. 

Just as a side note, there are also other (and more reliable) ways to show your site to Google than just letting it crawl the site, like a sitemap. 

Definitely an interesting issue, thank you for reporting!

**Comment by gmrchk** [comment] 2019-05-26 19:14
We have now a [head plugin](https://swup.js.org/plugins/head-plugin). Since the replacing of head content happens at a different time then the pushState, I'm not sure it will help to solve this situation. 

I'm also not sure we should invest in solving this tho since `canonical` tags are not essential for the page and could be potentially removed, or as mentioned, there are other ways of letting Google know about the site structure. 

Also, I'm not sure how this could be solved (in case the new head plugin doesn't help), since we can't replace the content of the head when the pushState happens, as we don't have the content at that time. 

I would definitely suggest to add this into a common issue.

Thoughts?

**Comment by gmrchk** [comment] 2019-07-20 15:31
Added a mention about this issue into docs [here](http://localhost:4000/common-issues). Closing, but can revisit if the problem is actually common.

**Closed by gmrchk** 2019-07-20 15:31 UTC
Labels: needs investigating
