### ISSUE TITLE
[Feature Request]: Expose AbortController to be able abort request programmatically

### ISSUE THREAD

**Issue by mskocik** [swup/swup#844] opened 2023-12-07 15:27 UTC
### Describe the problem 🧐

There is no way to programatically abort currently running request. For example when you want to display dialog for long running request if you want to abort given request.

Only way to cancel request is by setting `timeout`, which cannot be used for use case described.

### Describe the propsed solution 😎

Solution is simple, just add `AbortController` ~to `options`~ as a third parameter for `fetch:request` hook. 

https://github.com/swup/swup/blob/d2b0d8f5a0ad33ea0127e070f921aa01c7f0a464/src/modules/fetchPage.ts#L72-L77

### Alternatives considered 🤔

There is no alternative I can think of 🤷‍♂️ 

### How important is this feature to you? 🧭

I cannot use swup without it

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment] 2023-12-07 16:48
Interesting use case! With the recent introduction of an official `visit:abort` hook, I'd prefer extending that to allow aborting the whole visit instead of just the request.

In any case, you should currently be able to replace the internal hook and supply your own fetch request with a custom AbortController you'll have access to.

```js
swup.hooks.replace('fetch:request', (visit, { url, options }) => {
  const { signal } = new AbortController();
  return fetch(url, { ...options, signal });
});
```

While this will disable the internal timeout feature from working, you could look into [combining multiple AbortControllers into a single signal](https://github.com/whatwg/fetch/issues/905#issuecomment-491970649) or re-implement a timeout inside the replaced hook.

**Comment by hirasso** [comment] 2023-12-08 14:31
I vote for making `visit.abort()` public.

**Comment by mskocik** [comment] 2023-12-08 17:48
@daun Thanks for pointing that I can replace hook with custom implementation, I wasn't aware of this. I must have missed it in the docs (not sure it's there). But I believe it should be possible to do it natively, not by replacement, which would disable another built-in feature.

You can think of it as mimicking native browser functionality, that by pressign ESC you can stop current navigation. It's not possible to do easily. All 'abort' functionality is related to `visit:abort` hook, which is different use case - changing current navigation by another one, but not pure abort

@hirasso after looking into the code (just changing the state), not sure it is enough (but would be nice API if it handle abort correctly)

**Comment by daun** [comment] 2023-12-08 18:07
@hirasso Can you think of any downsides of exposing the `AbortController` in the `fetch:request` hook?

**Comment by mskocik** [comment] 2023-12-08 18:37
@daun 

> I'm wondering - have you tried calling `swup.navigate(swup.visit.from)` ?

It RE-fetches current page. 

> You can access the currently running visit on the swup instance.

Calling `abort()` doesn't undo navigation state (new url), don't reset progressbar, because `visit:end` is not called

> Hook replacement is intentionally left undocumented as it's an advanced feature and a bit of a potential foot gun.

I agree it's potentially dangerous, but could be mentioned somewhere as an "advanced" feature.

> What you're trying to do should already be possible.

I agree, thanks to ability to replace hook implementation, work-around exists.

**Comment by mskocik** [comment] 2023-12-08 18:42
btw are you sure, abort works as it should? When changing navigation to different page the first request still finishes (status 200), but only second page is shown. Or is it by design?

![image](https://github.com/swup/swup/assets/25513620/3a6e1948-086f-40ca-b925-6fa87abf2392)

**Comment by mskocik** [comment] 2023-12-08 19:33
Okay, after testing with providing my own `AbortController` as @daun suggested, I am getting uncaught error with this stack and swup breaks. Seems like async hook doesn't expect error to be thrown.

![image](https://github.com/swup/swup/assets/25513620/198b16f6-37cf-4716-ae5c-fc90fd8e67e5)

**Comment by daun** [comment] 2023-12-08 21:02
> are you sure, abort works as it should

No, we're not sure, but we appreciate you battle-testing it 🤠 Aborting visits is a [recent feature](https://github.com/swup/swup/releases/tag/4.5.0) meant to gracefully handle new visits when a visit is already running. Aborting a visit out of the blue the way you're suggesting is something that wasn't on our minds, so I'm pretty sure it's not 100% suited for that.

> When changing navigation to different page the first request still finishes (status 200), but only second page is shown. Or is it by design?

That's definitely by design. Considering this from an animation and user experience standpoint, in most cases you're looking to ignore the running visit and execute the new visit if a new link was clicked in the meantime to achieve smooth animations.

> Calling abort() doesn't undo navigation state (new url), don't reset progressbar, because visit:end is not called

Those are good points. Undoing the new URL is something to consider. The progress bar hiding on visit:abort is something that wasn't required with the use case we had in mind, but makes perfect sense. Feel free to create an issue or, even better, a PR, over on [the progress plugin repo](https://github.com/swup/progress-plugin).

**Comment by daun** [comment] 2023-12-09 09:51
I've created a new issue with a summary of this discussion and a few suggestions on how and whether to tackle this.

Closing, continued in #847.

**Closed by daun** 2023-12-09 09:51 UTC

**Comment by mskocik** [comment] 2023-12-12 14:15
> Can you share the exact code you're using to implement this? Hard so say for sure what's missing here.

Sorry for delayed answer...

```js
swup.hooks.replace('fetch:request', function(visit, { url, options }) {
  const abortController = new AbortController();
  setTimeout(() => {
    abortController.abort();
  }, 500)

  return fetch(url, { ...options, signal: abortController.signal });
});
```

**Comment by daun** [comment] 2023-12-12 14:36
@mskocik This is a bit of a hack, but you could try throwing `{ aborted: true }` after aborting the fetch. That's how swup itself throws this and how it knows to ignore the exception. Let us know if that works.

```js
setTimeout(() => {
  abortController.abort();
  throw { aborted: true };
}, 500)
```

**Comment by mskocik** [comment] 2023-12-12 15:23
In console:
![image](https://github.com/swup/swup/assets/25513620/1d7fc9c1-1def-497f-8346-18b21b03e351)

Network fetch request is aborted correctly, but `fetch:error` is not being called.

**Comment by daun** [comment] 2023-12-12 15:25
Then we're all out of options :) I'll try this out in my local playground to see how to enable your use case, but it probably needs to be implemented as a feature, if we want this functionality in the core.

**Comment by mskocik** [comment] 2023-12-12 15:29
I think it would/could be enough if the error is being handled or propagated when async hook is being triggered.

**Comment by daun** [comment] 2023-12-12 15:43
Propagating errors in hook handlers needs to be conditional on the type of exception; we need to tell the difference between error exceptions and exceptions thrown by aborting a request. One should crash and force a native browser reload, one should just be dropped silently. I'm not sure why it doesn't recognize the example code above as an aborted request; will need to look into that.

**Comment by daun** [comment] 2024-02-19 22:11
@mskocik After giving this an [earnest try](https://github.com/swup/swup/pull/850), we've decided not to implement this for the time being — the added complexity is too high for a feature we'll need to maintain going forward. Thanks again for bringing it up and we'll let you know if the feature ever gets revived!
