### ISSUE TITLE
Error when clicking two links in a short time

### ISSUE THREAD

**Issue by Kacperell** [swup/swup#237] opened 2020-01-05 11:33 UTC
Hi,  first of all thank you for swup library, it's awesome! I found problem.When we click quickly two links, the router jams and loads indefinitely. The same situation happens when click on the link and immediately press the back button. (this situation also happens on our documentation page). Although the first situation (quickly clicked two links) probably not happening on our site. Maybe because there is less content? Do you plan to solve this problem? Unfortunately, this error precludes swup.js from being used on a larger scale.  Thank you! 
![swup](https://user-images.githubusercontent.com/26602351/71779580-795ed480-2fb7-11ea-8aef-071158f4e67c.png)

**Comment by gmrchk** [comment] 2020-01-07 23:10
Hey @Kacperell and thanks!

Actually, we have this issue already in plans for fixing (https://github.com/swup/swup/issues/187). Unfortunately, I didn't have much time lately, but I'll get to it soon. In meanwhile, feel free to open a PR.

**Comment by gmrchk** [comment] 2020-01-07 23:18
Duplicate of #187

**Comment by gmrchk** [comment] 2020-03-01 18:59
Closing this ticked to avoid conversations in two places.

**Closed by gmrchk** 2020-03-01 18:59 UTC
