### ISSUE TITLE
 @swup/js-plugin: ^3.1.1 and @swup/scripts-plugin: ^2.0.0 break Astro formatting

### ISSUE THREAD

**Issue by kkopp001** [swup/swup#807] opened 2023-10-26 09:04 UTC
**Description of the issue**

When certain Swup plugins (@swup/js-plugin and @swup/scripts-plugin) are installed in an Astro project, the Astro code formatter stops working. This behavior was observed in a fresh Astro project, indicating a potential conflict between these Swup plugins and Astro's formatter.

**How to reproduce the issue**

1. Create a new Astro project using "npm create astro@latest".
2. Install the Swup plugins: npm install @swup/js-plugin @swup/scripts-plugin or yarn add @swup/js-plugin @swup/scripts-plugin.
3. Try using the Astro formatter. It will not format the code as expected.

**Context and environment**

No need to config anything, breaks once the packages are installed

**Before creating this issue...**

- [ x] Have you provided all helpful information available?
- [x ] Have you checked closed issues for similar/related problems?
- [ ] Have you considered creating a demo so we can help you better?

**Comment by hirasso** [comment] 2023-10-28 17:15
HI @kkopp001 

Could you be more specific? 

> Try using the Astro formatter

What formatter do you mean?

> It will not format the code as expected.

What code?

**Comment by kkopp001** [comment] 2023-10-31 10:22
Hi @hirasso,

When I mentioned the Astro formatter, I was referring to the official Astro extension in Visual Studio Code that formats the code.

Regarding your question about "what code", I meant the Astro code in my project. After installing the specified Swup plugins, I observed that the Astro code in my project wasn't being formatted as expected by the Astro extension in VSCode.

I hope this clarifies the issue better. Thank you for your patience.

**Comment by hirasso** [comment] 2023-10-31 11:09
@kkopp001 

- are you only installing the two plugins mentioned above, or are you even using them?
- What is the expected format of your code? (please provide a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- What is the actual (=broken) format of your code? (please provide a code block)

**Comment by hirasso** [comment] 2023-10-31 11:30
I suspect this could be happening due to the fact that the scripts-plugin isn't written in TypeScript, yet. I've created https://github.com/swup/scripts-plugin/pull/30, let's see if this solves the issue.

**Comment by hirasso** [comment] 2023-11-01 07:40
@kkopp001 could you update `@swup/scripts-plugin` to version 2.1.0 and test if your issue persists?

**Comment by hirasso** [comment] 2023-11-09 07:17
@kkopp001 any news on this? Otherwise, I'll close this as non-reproducible

**Closed** 2023-11-10 21:35 UTC
