### ISSUE TITLE
href="#anchor" links not working

### ISSUE THREAD

**Issue by foxnoodles** [swup/swup#349] opened 2021-03-21 13:19 UTC
So, basically any # links stopped working after enabling swap. The rest works just fine. 

I've tried tinkering around with link selector to no vail. 

adding [data-no-swap] to those elements does not fix the problem. Any ideas? direct code example would be nice since this is  a universal issue. I don't have any other scripts running that might prevent it from working.

**Comment by gmrchk** [comment] 2021-03-28 20:30
Duplicate of https://github.com/swup/swup/issues/267

**Closed by gmrchk** 2021-03-28 20:30 UTC
