### ISSUE TITLE
url lost param

### ISSUE THREAD

**Issue by ilyha81** [swup/swup#127] opened 2019-03-26 18:47 UTC
Hi!

I use urls like "*/tutorial?step=0" for get param and SWUP all this type of urls cut to "*/tutorial/" (but load correct page). If user reload page - he reload wrong url and get error "missing get param".

seems trouble happens when transition is from url "/tutorial?step=0" to "/tutorial?step=1"etc - swup just cut the params in url

**Comment by gmrchk** [comment] 2019-04-19 21:28
Hi @ilyha81, sorry for the late reply.

I can see the issue. I will fix this and let you know here.

**Comment by MartDSam** [comment] 2019-05-08 22:27
He loses the hash too. I think it has something to do with automatic scrolling to the top.

**Comment by gmrchk** [comment] 2019-07-20 15:47
Hi guys, @ilyha81 @MartDSam. 

I was just checking the issue and cannot reproduce. It's possible I "unknowingly" fixed this with all the changes for v2. Could you please confirm that this is fixed, or post steps for reproducing?

**Comment by MartDSam** [comment] 2019-07-25 18:53
The hash remains correctly now.

Only problem I don't know if it's really a problem is that if the URL has a hash the scroll doesn't respect the hash and scrolls to the top of the site.

**Comment by gmrchk** [comment] 2019-07-27 01:14
If you're referring to browser not scrolling to the hash when going back/forward, then browser act's the same without swup, it will jump to the last known location - swup actually let's browser take care of that. When `animateHistoryBrowsing` is enabled, swup will scroll to the hash element. 

Anyway, seems we're good here, so closing. Please, let me know in case this still causes some problems. Thanks for reporting!

**Closed by gmrchk** 2019-07-27 01:14 UTC
Labels: bug
